# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
        image: redis:alpine
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 6379:6379
      memcached:
        image: memcached:alpine
        ports:
          - 11211:11211
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - name: Install PostgreSQL client
        run: sudo apt-get install libpq-dev

      - name: Install dependencies and create DB
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASS: postgres
          PGPORT: 5432
          RAILS_ENV: test
        run: |
          bundle exec rake db:setup
      - name: Run tests
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGPASS: postgres
          PGPORT: 5432
          REDISCLOUD_URL: redis://localhost:6379
          RAILS_ENV: test
          MEMCACHE_SERVERS: localhost
        run: |
          bundle exec rspec
      - name: Upload coverage for Sonarcloud
        uses: actions/upload-artifact@v3
        with:
          name: rspec_track
          path: ./coverage/.resultset.json


  # RUN RUBOCOP
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true

      - uses: actions/cache@v3
        with:
          path: vendor/rubocop_cache
          key: ${{ runner.os }}-rubocop-cache
          restore-keys: |
            ${{ runner.os }}-rubocop-cache

      - name: Rubocop
        run: |
          bundle exec rubocop --parallel --cache-root vendor/rubocop_cache

  # RUN RUBYCRITIC
  rubycritic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0

      - name: Run Rubycritic
        run: |
          gem install reek -v 6.1.4 --no-document
          gem install rubycritic --no-document
          rubycritic

  # FAST FAIL
  fast_fail:
    runs-on: ubuntu-latest
    needs: [rubocop, rubycritic]
    if: failure()

    steps:
      - name: Fail current workflow
        uses: andymckay/cancel-action@0.3
